### ISSUE TITLE
How to deploy this app?

### ISSUE THREAD

**Issue by rdjanati** [abhineet97/webrtc-chess#4]
Hi,

Can you please help with instructions to execute and run this game?

Thank you,
Rabah

**Comment by abhineet97** [comment]
Hi!
The server is written in the Golang, so you'll need to download and install it to build the `server.go` file. For the front-end, you'll need NodeJS/NPM.
I'll upload detailed instructions on how to build the game in the future. For now, if you would like to try the game then you can do so [here](https://abhineet.tk/webrtc-chess).

**Comment by abhineet97** [comment]
I've added build instructions to the README.
Hope that helps you in deploying this app.
